ALTER SEQUENCE departments_id_seq RESTART WITH 1000;
ALTER SEQUENCE employees_id_seq   RESTART WITH 2000;
ALTER SEQUENCE projects_id_seq    RESTART WITH 3000;
ALTER SEQUENCE products_id_seq    RESTART WITH 4000;
ALTER SEQUENCE investments_id_seq RESTART WITH 5000;