-- Products are the deliverable items and subsystems the programs consume.
-- category groups them for the catalog filters and the reporting screens.
INSERT INTO products (id, name, category, description, unit_cost) VALUES
(4000, 'Autonomous Ground Vehicle Hull', 'Platform',       'Armored hull and suspension assembly',            1250000.00),
(4001, 'Electro-Optical Camera Module',  'Sensor',         'Day and night imaging unit',                       420000.00),
(4002, 'LIDAR Sensor Unit',              'Sensor',         '360 degree 3D scanning sensor',                    185000.00),
(4003, 'INS/GNSS Navigation Unit',       'Avionics',       'Inertial navigation and satellite positioning',    310000.00),
(4004, 'Mission Computer',               'Avionics',       'Embedded real-time processing unit',               145000.00),
(4005, 'Encrypted Radio Module',         'Communication',  'Frequency hopping encrypted data link',            265000.00),
(4006, 'Ground Control Station',         'Ground Systems', 'Portable operator console',                        680000.00),
(4007, 'Power Distribution Unit',        'Electronics',    'On-platform energy management',                      75000.00),
(4008, 'Weapon Stabilization System',    'Platform',       'Two-axis stabilized turret',                       890000.00),
(4009, 'Radar Signal Processor Board',   'Electronics',    'FPGA based signal processing board',               230000.00),
(4010, 'Active Antenna Array',           'Sensor',         'Gallium nitride transmit and receive module array', 2400000.00),
(4011, 'Thermal Imaging Core',           'Sensor',         'Cooled mid-wave infrared detector core',           540000.00),
(4012, 'Laser Range Finder',             'Sensor',         'Eye-safe ranging and target designation unit',     195000.00),
(4013, 'Flight Control Computer',        'Avionics',       'Triple redundant flight control unit',             620000.00),
(4014, 'Air Data Sensor Boom',           'Avionics',       'Pitot-static and angle of attack probe',            88000.00),
(4015, 'Satellite Modem',                'Communication',  'Ka-band transmit and receive modem',               355000.00),
(4016, 'Tactical Data Link Terminal',    'Communication',  'Standards compliant tactical data link terminal',  780000.00),
(4017, 'Antenna Positioner',             'Ground Systems', 'Motorized two-axis antenna mount',                 265000.00),
(4018, 'Shelter Rack Assembly',          'Ground Systems', 'Shock isolated 19 inch equipment rack',             42000.00),
(4019, 'Operator Display Console',       'Ground Systems', 'Ruggedized dual screen workstation',               148000.00),
(4020, 'Battery Pack Module',            'Electronics',    'Lithium-ion energy storage module',                 36000.00),
(4021, 'Signal Conditioning Card',       'Electronics',    'Analog front end and filtering card',               28000.00),
(4022, 'Hardened Ethernet Switch',       'Electronics',    'Military grade managed network switch',              54000.00),
(4023, 'Turbofan Engine Module',         'Propulsion',     'Small expendable turbofan assembly',              1850000.00),
(4024, 'Electric Propulsion Motor',      'Propulsion',     'Brushless traction motor and controller',           265000.00),
(4025, 'Solid Rocket Booster',           'Propulsion',     'Short burn launch assist motor',                   940000.00),
(4026, 'Mission Planning Suite',         'Software',       'Route planning and payload tasking software',       320000.00),
(4027, 'Health Monitoring Software',     'Software',       'Onboard diagnostics and prognostics package',       165000.00),
(4028, 'Cryptographic Key Loader',       'Communication',  'Portable key fill and zeroize device',              118000.00),
(4029, 'Composite Fuselage Panel',       'Materials',      'Carbon fibre structural panel',                      76000.00),
(4030, 'Radar Absorbent Coating',        'Materials',      'Low observable surface treatment kit',              132000.00),
(4031, 'Environmental Test Chamber',     'Ground Systems', 'Temperature and humidity qualification chamber',   1450000.00);

SELECT setval('products_id_seq', (SELECT MAX(id) FROM products));
