"""The rule set. Every rule is a pure function: Schema in, findings out.

Two things are deliberate here. Rules never run SQL, so they can be exercised
against a hand-built Schema in a test. And a rule that cannot know the right
answer says so through Remediation.requires_decision instead of guessing - the
correct ON DELETE for a business table is a policy question, not a lookup.
"""

from .model import ERROR, INFO, WARNING, Finding, Remediation, Schema


def _q(schema: Schema, table: str) -> str:
    return f"{schema.name}.{table}"


def _recreate_fk(schema: Schema, fk, on_delete: str, on_update: str) -> str:
    """DDL that replaces a foreign key with one that spells out both actions.

    Dropping and re-adding inside a single ALTER TABLE keeps it atomic, so the
    table is never briefly unconstrained.
    """
    columns = ", ".join(fk.columns)
    target_columns = ", ".join(fk.target_columns)
    return (
        f"ALTER TABLE {_q(schema, fk.table)}\n"
        f"    DROP CONSTRAINT {fk.name},\n"
        f"    ADD CONSTRAINT {fk.name}\n"
        f"        FOREIGN KEY ({columns})\n"
        f"        REFERENCES {_q(schema, fk.target_table)} ({target_columns})\n"
        f"        ON DELETE {on_delete} ON UPDATE {on_update};"
    )


# --------------------------------------------------------------------------
# R001 - primary key
# --------------------------------------------------------------------------


def missing_primary_key(schema: Schema) -> list[Finding]:
    findings = []
    for name in sorted(schema.tables):
        table = schema.tables[name]
        if table.primary_key:
            continue

        remediations = []
        for unique in table.unique_sets:
            columns = ", ".join(unique)
            remediations.append(
                Remediation(
                    label=f"Promote the existing UNIQUE ({columns}) to primary key",
                    ddl=f"ALTER TABLE {_q(schema, name)} ADD PRIMARY KEY ({columns});",
                    risk="medium",
                    recommended=True,
                    note="Every listed column has to be NOT NULL before this runs.",
                )
            )
        remediations.append(
            Remediation(
                label="Add a surrogate key column",
                ddl=(
                    f"ALTER TABLE {_q(schema, name)}\n"
                    f"    ADD COLUMN id integer GENERATED BY DEFAULT AS IDENTITY"
                    f" PRIMARY KEY;"
                ),
                risk="medium",
                recommended=not table.unique_sets,
                note="Rewrites the table; on a large one use a maintenance window.",
            )
        )

        findings.append(
            Finding(
                rule_id="R001",
                rule_name="Missing primary key",
                severity=ERROR,
                target=_q(schema, name),
                message=f'Table "{name}" has no primary key.',
                rationale=(
                    "Without a primary key there is no way to address a single "
                    "row, duplicates cannot be prevented, no other table can "
                    "reference this one, and most replication and ORM tooling "
                    "refuses to work with the table."
                ),
                remediations=tuple(remediations),
            )
        )
    return findings


# --------------------------------------------------------------------------
# R002 / R003 - referential actions
# --------------------------------------------------------------------------


def undefined_on_delete(schema: Schema) -> list[Finding]:
    findings = []
    for fk in schema.foreign_keys:
        if fk.on_delete != "NO ACTION":
            continue

        table = schema.tables[fk.table]
        nullable = all(
            (column := table.column(name)) is not None and not column.not_null
            for name in fk.columns
        )

        remediations = []
        if schema.is_junction(fk.table):
            remediations.append(
                Remediation(
                    label="Delete the link row with its parent",
                    ddl=_recreate_fk(schema, fk, "CASCADE", fk.on_update),
                    risk="medium",
                    recommended=True,
                    note=(
                        f'"{fk.table}" is a link table, so a row here has no '
                        f"meaning once the {fk.target_table} row is gone."
                    ),
                )
            )
        else:
            remediations.append(
                Remediation(
                    label="Refuse the delete while children exist (write it down)",
                    ddl=_recreate_fk(schema, fk, "RESTRICT", fk.on_update),
                    risk="low",
                    recommended=True,
                    note=(
                        "Behaves exactly like the database does today - this "
                        "only makes the intent explicit in the schema."
                    ),
                )
            )
            if nullable:
                remediations.append(
                    Remediation(
                        label="Keep the child row, clear the reference",
                        ddl=_recreate_fk(schema, fk, "SET NULL", fk.on_update),
                        risk="medium",
                        requires_decision=True,
                        note=(
                            f"Pick this if a {fk.table} row should outlive its "
                            f"{fk.target_table}."
                        ),
                    )
                )
            remediations.append(
                Remediation(
                    label="Delete the child rows too",
                    ddl=_recreate_fk(schema, fk, "CASCADE", fk.on_update),
                    risk="high",
                    requires_decision=True,
                    note=(
                        f"Destructive: removing one {fk.target_table} row would "
                        f"silently delete every matching {fk.table} row."
                    ),
                )
            )

        findings.append(
            Finding(
                rule_id="R002",
                rule_name="Undefined ON DELETE behaviour",
                severity=WARNING,
                target=fk.name,
                message=f"{fk.label} falls back to ON DELETE NO ACTION.",
                rationale=(
                    "The catalog cannot tell an omitted clause from an explicit "
                    "ON DELETE NO ACTION, which is exactly the problem: a reader "
                    "cannot tell whether refusing the delete was a decision or "
                    "an oversight. Writing the action down removes the ambiguity "
                    "without changing behaviour."
                ),
                remediations=tuple(remediations),
            )
        )
    return findings


def undefined_on_update(schema: Schema) -> list[Finding]:
    findings = []
    for fk in schema.foreign_keys:
        if fk.on_update != "NO ACTION":
            continue
        findings.append(
            Finding(
                rule_id="R003",
                rule_name="Undefined ON UPDATE behaviour",
                severity=INFO,
                target=fk.name,
                message=f"{fk.label} falls back to ON UPDATE NO ACTION.",
                rationale=(
                    "Low priority while the referenced key is generated and "
                    "never edited, because the action simply never fires. It is "
                    "still worth stating so the schema stops depending on that "
                    "assumption holding forever."
                ),
                remediations=(
                    Remediation(
                        label="State the current behaviour explicitly",
                        ddl=_recreate_fk(schema, fk, fk.on_delete, "RESTRICT"),
                        risk="low",
                        recommended=True,
                        note="No behavioural change; documents the intent.",
                    ),
                    Remediation(
                        label="Follow the parent key when it changes",
                        ddl=_recreate_fk(schema, fk, fk.on_delete, "CASCADE"),
                        risk="medium",
                        requires_decision=True,
                        note="Only needed if the referenced key is ever updated.",
                    ),
                ),
            )
        )
    return findings


# --------------------------------------------------------------------------
# R004 - isolated tables
# --------------------------------------------------------------------------


def isolated_table(schema: Schema) -> list[Finding]:
    findings = []
    for name in sorted(schema.tables):
        if schema.outgoing(name) or schema.incoming(name):
            continue
        findings.append(
            Finding(
                rule_id="R004",
                rule_name="Isolated table",
                severity=INFO,
                target=_q(schema, name),
                message=f'Table "{name}" has no foreign key in either direction.',
                rationale=(
                    "Either it genuinely stands alone - a lookup list, an audit "
                    "log, a migration ledger - or it is joined in application "
                    "code through a relationship the database does not enforce. "
                    "The second case is where orphan rows come from."
                ),
                confidence="heuristic",
                remediations=(
                    Remediation(
                        label="Confirm the table is standalone by design",
                        ddl="",
                        risk="low",
                        recommended=True,
                        note=(
                            "If it is, add it to the rule's ignore list so the "
                            "report stays free of known-good findings."
                        ),
                    ),
                    Remediation(
                        label="Declare the missing relationship",
                        ddl=(
                            f"ALTER TABLE {_q(schema, name)}\n"
                            f"    ADD CONSTRAINT {name}_<parent>_id_fkey\n"
                            f"        FOREIGN KEY (<parent>_id)\n"
                            f"        REFERENCES {schema.name}.<parent> (id)\n"
                            f"        ON DELETE RESTRICT ON UPDATE RESTRICT;"
                        ),
                        risk="medium",
                        requires_decision=True,
                        note="Template - fill in the parent table and column.",
                    ),
                ),
            )
        )
    return findings


# --------------------------------------------------------------------------
# R005 - circular foreign key chains
# --------------------------------------------------------------------------


def _cycle_key(cycle: list[str]) -> tuple[str, ...]:
    """Rotates a cycle so the same loop is never reported twice."""
    start = cycle.index(min(cycle))
    return tuple(cycle[start:] + cycle[:start])


def circular_foreign_keys(schema: Schema) -> list[Finding]:
    # A self-reference (employees.manager_id -> employees) is a normal way to
    # model a hierarchy, so it is not treated as a cycle.
    edges: dict[str, set[str]] = {}
    for fk in schema.foreign_keys:
        if fk.table != fk.target_table:
            edges.setdefault(fk.table, set()).add(fk.target_table)

    cycles: dict[tuple[str, ...], None] = {}
    visited: set[str] = set()
    stack: list[str] = []
    on_stack: set[str] = set()

    def visit(node: str) -> None:
        visited.add(node)
        stack.append(node)
        on_stack.add(node)
        for target in sorted(edges.get(node, ())):
            if target in on_stack:
                cycles.setdefault(_cycle_key(stack[stack.index(target) :]), None)
            elif target not in visited:
                visit(target)
        stack.pop()
        on_stack.discard(node)

    for table in sorted(schema.tables):
        if table not in visited:
            visit(table)

    findings = []
    for key in sorted(cycles):
        path = " -> ".join(key) + f" -> {key[0]}"
        findings.append(
            Finding(
                rule_id="R005",
                rule_name="Circular foreign key chain",
                severity=ERROR,
                target=", ".join(key),
                message=f"Foreign keys form a loop: {path}.",
                rationale=(
                    "Nothing in the loop can be inserted first, so the rows can "
                    "only be created by deferring a constraint or by leaving a "
                    "column NULL and filling it in afterwards. Deleting the "
                    "group has the same problem in reverse."
                ),
                remediations=(
                    Remediation(
                        label="Defer one constraint in the loop to break it",
                        ddl=(
                            f"-- Pick the least important link in the loop:\n"
                            f"ALTER TABLE {schema.name}.<table>\n"
                            f"    DROP CONSTRAINT <constraint>,\n"
                            f"    ADD CONSTRAINT <constraint>\n"
                            f"        FOREIGN KEY (<column>)\n"
                            f"        REFERENCES {schema.name}.<target> (id)\n"
                            f"        DEFERRABLE INITIALLY DEFERRED;"
                        ),
                        risk="medium",
                        requires_decision=True,
                        note="Lets one transaction insert the whole group at once.",
                    ),
                    Remediation(
                        label="Move the weakest link into a separate table",
                        ddl="",
                        risk="high",
                        requires_decision=True,
                        note=(
                            "The structural fix: replace one direct reference "
                            "with a link table so the loop disappears."
                        ),
                    ),
                ),
            )
        )
    return findings


# --------------------------------------------------------------------------
# R006 - duplicate and redundant indexes
# --------------------------------------------------------------------------


def redundant_index(schema: Schema) -> list[Finding]:
    findings = []
    for name in sorted(schema.tables):
        table = schema.tables[name]
        reported: set[str] = set()

        by_columns: dict[tuple[str, ...], list] = {}
        for index in table.indexes:
            by_columns.setdefault(index.columns, []).append(index)

        # Exact duplicates: same columns in the same order.
        for columns, group in sorted(by_columns.items()):
            if len(group) < 2:
                continue
            # Keep the primary key, then any unique index - those carry a
            # guarantee, not just an access path.
            group = sorted(
                group, key=lambda ix: (not ix.is_primary, not ix.is_unique, ix.name)
            )
            keep, extras = group[0], group[1:]
            for extra in extras:
                reported.add(extra.name)
                findings.append(
                    Finding(
                        rule_id="R006",
                        rule_name="Duplicate index",
                        severity=WARNING,
                        target=f"{_q(schema, name)}.{extra.name}",
                        message=(
                            f'"{extra.name}" indexes ({", ".join(columns)}), '
                            f'which "{keep.name}" already covers.'
                        ),
                        rationale=(
                            "A second copy of the same index is written on every "
                            "insert, update and delete, costs disk and cache, "
                            "and is never chosen by the planner over the first."
                        ),
                        remediations=(
                            Remediation(
                                label=f"Drop {extra.name}",
                                ddl=f"DROP INDEX {schema.name}.{extra.name};",
                                risk="medium" if extra.is_unique else "low",
                                recommended=not extra.is_unique,
                                note=(
                                    "This one also enforces uniqueness - check "
                                    "nothing depends on the constraint name."
                                    if extra.is_unique
                                    else "Pure duplicate; safe to remove."
                                ),
                            ),
                        ),
                    )
                )

        # Prefix redundancy: an index on (a) is dead weight when (a, b) exists.
        for index in sorted(table.indexes, key=lambda ix: ix.name):
            if index.is_primary or index.is_unique or index.name in reported:
                continue
            wider = [
                other.name
                for other in table.indexes
                if other.name != index.name
                and len(other.columns) > len(index.columns)
                and other.covers(index.columns)
            ]
            if not wider:
                continue
            covering = sorted(wider)[0]
            findings.append(
                Finding(
                    rule_id="R006",
                    rule_name="Redundant index prefix",
                    severity=INFO,
                    target=f"{_q(schema, name)}.{index.name}",
                    message=(
                        f'"{index.name}" on ({", ".join(index.columns)}) is a '
                        f'leading subset of "{covering}".'
                    ),
                    rationale=(
                        "A composite index already serves lookups that start at "
                        "its first columns, so the narrower index only adds "
                        "write cost."
                    ),
                    remediations=(
                        Remediation(
                            label=f"Drop {index.name}",
                            ddl=f"DROP INDEX {schema.name}.{index.name};",
                            risk="low",
                            recommended=True,
                            note=f'"{covering}" keeps serving the same lookups.',
                        ),
                    ),
                )
            )
    return findings


# --------------------------------------------------------------------------
# R007 - foreign key type mismatch
# --------------------------------------------------------------------------


def foreign_key_type_mismatch(schema: Schema) -> list[Finding]:
    findings = []
    for fk in schema.foreign_keys:
        source = schema.tables.get(fk.table)
        target = schema.tables.get(fk.target_table)
        if source is None or target is None:
            continue
        for column_name, target_name in zip(fk.columns, fk.target_columns):
            column = source.column(column_name)
            target_column = target.column(target_name)
            if column is None or target_column is None:
                continue
            if column.type_oid == target_column.type_oid:
                continue
            findings.append(
                Finding(
                    rule_id="R007",
                    rule_name="Foreign key type mismatch",
                    severity=ERROR,
                    target=f"{_q(schema, fk.table)}.{column_name}",
                    message=(
                        f"{fk.table}.{column_name} is {column.data_type} but "
                        f"{fk.target_table}.{target_name} is "
                        f"{target_column.data_type}."
                    ),
                    rationale=(
                        "PostgreSQL allows a foreign key between comparable but "
                        "different types. Every join across it then needs a "
                        "cast, which can stop an index from being used, and the "
                        "narrower side overflows long before the wider one."
                    ),
                    remediations=(
                        Remediation(
                            label=(
                                f"Widen {fk.table}.{column_name} to "
                                f"{target_column.data_type}"
                            ),
                            ddl=(
                                f"ALTER TABLE {_q(schema, fk.table)}\n"
                                f"    ALTER COLUMN {column_name} TYPE "
                                f"{target_column.data_type};"
                            ),
                            risk="medium",
                            recommended=True,
                            note="Rewrites the table and rebuilds its indexes.",
                        ),
                    ),
                )
            )
    return findings


# --------------------------------------------------------------------------
# R008 - unindexed foreign keys
# --------------------------------------------------------------------------


def unindexed_foreign_key(schema: Schema) -> list[Finding]:
    findings = []
    for fk in schema.foreign_keys:
        table = schema.tables.get(fk.table)
        if table is None or not fk.columns:
            continue
        if any(index.covers(fk.columns) for index in table.indexes):
            continue

        columns = ", ".join(fk.columns)
        index_name = f"idx_{fk.table}_{'_'.join(fk.columns)}"
        findings.append(
            Finding(
                rule_id="R008",
                rule_name="Unindexed foreign key",
                severity=WARNING,
                target=f"{_q(schema, fk.table)}.{columns}",
                message=f"No index starts with ({columns}) on {fk.table}.",
                rationale=(
                    "PostgreSQL indexes the parent side of a foreign key but "
                    "never the child side. Every join across it, and every "
                    "delete on the parent - which has to look for children - "
                    "falls back to a sequential scan. On a composite primary "
                    "key only the first column is covered, which is why the "
                    "second column of a link table usually lands here."
                ),
                remediations=(
                    Remediation(
                        label=f"Create an index on ({columns})",
                        ddl=(
                            f"CREATE INDEX {index_name}\n"
                            f"    ON {_q(schema, fk.table)} ({columns});"
                        ),
                        risk="low",
                        recommended=True,
                        note=(
                            "Add CONCURRENTLY on a busy table to avoid taking a "
                            "write lock."
                        ),
                    ),
                ),
            )
        )
    return findings


# --------------------------------------------------------------------------
# R009 - relationships the database does not enforce
# --------------------------------------------------------------------------


def _guess_target_table(schema: Schema, base: str) -> str | None:
    candidates = [base, f"{base}s", f"{base}es"]
    if base.endswith("y"):
        candidates.append(f"{base[:-1]}ies")
    for candidate in candidates:
        if candidate in schema.tables:
            return candidate
    return None


def implied_foreign_key(schema: Schema) -> list[Finding]:
    findings = []
    for name in sorted(schema.tables):
        table = schema.tables[name]
        constrained = {column for fk in schema.outgoing(name) for column in fk.columns}
        for column in table.columns:
            if not column.name.endswith("_id") or column.name in constrained:
                continue
            target = _guess_target_table(schema, column.name[:-3])
            if target is None or target == name:
                continue

            findings.append(
                Finding(
                    rule_id="R009",
                    rule_name="Implied relationship without a foreign key",
                    severity=WARNING,
                    target=f"{_q(schema, name)}.{column.name}",
                    message=(
                        f'"{name}.{column.name}" looks like a reference to '
                        f'"{target}" but no foreign key enforces it.'
                    ),
                    rationale=(
                        "Nothing stops a value that matches no parent row. The "
                        "database will keep the orphans quietly, and they "
                        "usually surface much later as rows that disappear from "
                        "an inner join."
                    ),
                    confidence="heuristic",
                    remediations=(
                        Remediation(
                            label="Check for orphans first",
                            ddl=(
                                f"SELECT COUNT(*)\n"
                                f"FROM {_q(schema, name)} child\n"
                                f"LEFT JOIN {_q(schema, target)} parent\n"
                                f"       ON parent.id = child.{column.name}\n"
                                f"WHERE child.{column.name} IS NOT NULL\n"
                                f"  AND parent.id IS NULL;"
                            ),
                            risk="low",
                            recommended=True,
                            note=(
                                "Read-only. The constraint below cannot be added "
                                "until this returns 0."
                            ),
                        ),
                        Remediation(
                            label="Add the foreign key",
                            ddl=(
                                f"ALTER TABLE {_q(schema, name)}\n"
                                f"    ADD CONSTRAINT {name}_{column.name}_fkey\n"
                                f"        FOREIGN KEY ({column.name})\n"
                                f"        REFERENCES {_q(schema, target)} (id)\n"
                                f"        ON DELETE RESTRICT ON UPDATE RESTRICT;"
                            ),
                            risk="medium",
                            requires_decision=True,
                            note="Confirm the guessed target table is the right one.",
                        ),
                    ),
                )
            )
    return findings


# --------------------------------------------------------------------------
# R010 - the same column name declared differently
# --------------------------------------------------------------------------


def inconsistent_column_type(schema: Schema) -> list[Finding]:
    usage: dict[str, dict[str, list[str]]] = {}
    for name in sorted(schema.tables):
        for column in schema.tables[name].columns:
            usage.setdefault(column.name, {}).setdefault(column.data_type, []).append(
                name
            )

    findings = []
    for column_name in sorted(usage):
        variants = usage[column_name]
        if len(variants) < 2:
            continue

        # The type used by the most tables wins; ties go to the longer
        # declaration, since that is the one able to hold every existing value.
        preferred = sorted(
            variants,
            key=lambda type_name: (-len(variants[type_name]), -len(type_name)),
        )[0]
        summary = "; ".join(
            f"{type_name} in {', '.join(sorted(tables))}"
            for type_name, tables in sorted(variants.items())
        )

        remediations = []
        for type_name, tables in sorted(variants.items()):
            if type_name == preferred:
                continue
            for table_name in sorted(tables):
                remediations.append(
                    Remediation(
                        label=f"Align {table_name}.{column_name} to {preferred}",
                        ddl=(
                            f"ALTER TABLE {_q(schema, table_name)}\n"
                            f"    ALTER COLUMN {column_name} TYPE {preferred};"
                        ),
                        risk="medium",
                        requires_decision=True,
                        note=(
                            "Only if the two columns really hold the same kind "
                            "of value - a shared name is not proof of that."
                        ),
                    )
                )

        findings.append(
            Finding(
                rule_id="R010",
                rule_name="Inconsistent type for a shared column name",
                severity=INFO,
                target=column_name,
                message=f'"{column_name}" is declared differently: {summary}.',
                rationale=(
                    "Columns that mean the same thing should be declared the "
                    "same way. Mixed widths produce values that fit in one table "
                    "but are rejected when the same data moves to another."
                ),
                confidence="heuristic",
                remediations=tuple(remediations),
            )
        )
    return findings
