"""The rule set. Every rule is a pure function: Schema in, findings out.

Identifiers, DDL and these comments stay English like the rest of the codebase;
the prose a rule produces is Turkish, because that text is read by whoever has
to act on the finding.

Two things are deliberate here. Rules never run SQL, so they can be exercised
against a hand-built Schema in a test. And a rule that cannot know the right
answer says so through Remediation.requires_decision instead of guessing - the
correct ON DELETE for a business table is a policy question, not a lookup.
"""

from .model import ERROR, INFO, WARNING, Finding, Remediation, Schema


def _q(schema: Schema, table: str) -> str:
    return f"{schema.name}.{table}"


def _recreate_fk(schema: Schema, fk, on_delete: str, on_update: str) -> str:
    """DDL that replaces a foreign key with one that spells out both actions.

    Dropping and re-adding inside a single ALTER TABLE keeps it atomic, so the
    table is never briefly unconstrained.
    """
    columns = ", ".join(fk.columns)
    target_columns = ", ".join(fk.target_columns)
    return (
        f"ALTER TABLE {_q(schema, fk.table)}\n"
        f"    DROP CONSTRAINT {fk.name},\n"
        f"    ADD CONSTRAINT {fk.name}\n"
        f"        FOREIGN KEY ({columns})\n"
        f"        REFERENCES {_q(schema, fk.target_table)} ({target_columns})\n"
        f"        ON DELETE {on_delete} ON UPDATE {on_update};"
    )


# --------------------------------------------------------------------------
# R001 - primary key
# --------------------------------------------------------------------------


def missing_primary_key(schema: Schema) -> list[Finding]:
    findings = []
    for name in sorted(schema.tables):
        table = schema.tables[name]
        if table.primary_key:
            continue

        remediations = []
        for unique in table.unique_sets:
            columns = ", ".join(unique)
            remediations.append(
                Remediation(
                    label=f"Mevcut UNIQUE ({columns}) kısıtını birincil anahtara yükselt",
                    ddl=f"ALTER TABLE {_q(schema, name)} ADD PRIMARY KEY ({columns});",
                    risk="medium",
                    recommended=True,
                    note="Listedeki her kolonun önce NOT NULL olması gerekir.",
                )
            )
        remediations.append(
            Remediation(
                label="Yapay (surrogate) anahtar kolonu ekle",
                ddl=(
                    f"ALTER TABLE {_q(schema, name)}\n"
                    f"    ADD COLUMN id integer GENERATED BY DEFAULT AS IDENTITY"
                    f" PRIMARY KEY;"
                ),
                risk="medium",
                recommended=not table.unique_sets,
                note=(
                    "Tabloyu baştan yazar; büyük bir tabloda bakım penceresinde "
                    "çalıştır."
                ),
            )
        )

        findings.append(
            Finding(
                rule_id="R001",
                rule_name="Birincil anahtar yok",
                severity=ERROR,
                target=_q(schema, name),
                message=f'"{name}" tablosunda birincil anahtar yok.',
                rationale=(
                    "Birincil anahtar olmadan tek bir satırı adresleyebilmenin "
                    "yolu yoktur; yinelenen kayıtlar engellenemez, başka hiçbir "
                    "tablo bu tabloya referans veremez ve çoğu replikasyon ile "
                    "ORM aracı tabloyla çalışmayı reddeder."
                ),
                remediations=tuple(remediations),
            )
        )
    return findings


# --------------------------------------------------------------------------
# R002 / R003 - referential actions
# --------------------------------------------------------------------------


def undefined_on_delete(schema: Schema) -> list[Finding]:
    findings = []
    for fk in schema.foreign_keys:
        if fk.on_delete != "NO ACTION":
            continue

        table = schema.tables[fk.table]
        nullable = all(
            (column := table.column(name)) is not None and not column.not_null
            for name in fk.columns
        )

        remediations = []
        if schema.is_junction(fk.table):
            remediations.append(
                Remediation(
                    label="Bağlantı satırını üst kayıtla birlikte sil",
                    ddl=_recreate_fk(schema, fk, "CASCADE", fk.on_update),
                    risk="medium",
                    recommended=True,
                    note=(
                        f'"{fk.table}" bir bağlantı tablosu; ilgili '
                        f"{fk.target_table} satırı gidince buradaki satırın "
                        f"anlamı kalmaz."
                    ),
                )
            )
        else:
            remediations.append(
                Remediation(
                    label="Alt kayıt varken silmeyi reddet (açıkça yaz)",
                    ddl=_recreate_fk(schema, fk, "RESTRICT", fk.on_update),
                    risk="low",
                    recommended=True,
                    note=(
                        "Veritabanının bugün yaptığının aynısı - bu yalnızca "
                        "niyeti şemada görünür kılar."
                    ),
                )
            )
            if nullable:
                remediations.append(
                    Remediation(
                        label="Alt kaydı koru, referansı boşalt",
                        ddl=_recreate_fk(schema, fk, "SET NULL", fk.on_update),
                        risk="medium",
                        requires_decision=True,
                        note=(
                            f"Bir {fk.table} satırı, bağlı olduğu "
                            f"{fk.target_table} kaydından sonra da yaşamalıysa "
                            f"bunu seç."
                        ),
                    )
                )
            remediations.append(
                Remediation(
                    label="Alt kayıtları da sil",
                    ddl=_recreate_fk(schema, fk, "CASCADE", fk.on_update),
                    risk="high",
                    requires_decision=True,
                    note=(
                        f"Yıkıcı: tek bir {fk.target_table} satırını silmek, "
                        f"eşleşen bütün {fk.table} satırlarını sessizce siler."
                    ),
                )
            )

        findings.append(
            Finding(
                rule_id="R002",
                rule_name="Tanımsız ON DELETE davranışı",
                severity=WARNING,
                target=fk.name,
                message=f"{fk.label} ilişkisi ON DELETE NO ACTION'a düşüyor.",
                rationale=(
                    "Katalog, hiç yazılmamış bir ifadeyi açıkça yazılmış "
                    "ON DELETE NO ACTION'dan ayırt edemez; sorunun kendisi de "
                    "budur: okuyan kişi silmeyi reddetmenin bilinçli bir karar "
                    "mı yoksa gözden kaçmış bir eksik mi olduğunu anlayamaz. "
                    "Davranışı açıkça yazmak, hiçbir şeyi değiştirmeden bu "
                    "belirsizliği ortadan kaldırır."
                ),
                remediations=tuple(remediations),
            )
        )
    return findings


def undefined_on_update(schema: Schema) -> list[Finding]:
    findings = []
    for fk in schema.foreign_keys:
        if fk.on_update != "NO ACTION":
            continue
        findings.append(
            Finding(
                rule_id="R003",
                rule_name="Tanımsız ON UPDATE davranışı",
                severity=INFO,
                target=fk.name,
                message=f"{fk.label} ilişkisi ON UPDATE NO ACTION'a düşüyor.",
                rationale=(
                    "Referans verilen anahtar otomatik üretiliyor ve hiç "
                    "değiştirilmiyorsa önceliği düşüktür, çünkü bu davranış hiç "
                    "tetiklenmez. Yine de şemanın bu varsayımın sonsuza kadar "
                    "geçerli kalmasına dayanmaması için yazılmaya değer."
                ),
                remediations=(
                    Remediation(
                        label="Mevcut davranışı açıkça belirt",
                        ddl=_recreate_fk(schema, fk, fk.on_delete, "RESTRICT"),
                        risk="low",
                        recommended=True,
                        note="Davranış değişmez; yalnızca niyeti belgeler.",
                    ),
                    Remediation(
                        label="Üst anahtar değişince onu takip et",
                        ddl=_recreate_fk(schema, fk, fk.on_delete, "CASCADE"),
                        risk="medium",
                        requires_decision=True,
                        note=(
                            "Yalnızca referans verilen anahtar güncelleniyorsa "
                            "gereklidir."
                        ),
                    ),
                ),
            )
        )
    return findings


# --------------------------------------------------------------------------
# R004 - isolated tables
# --------------------------------------------------------------------------


def isolated_table(schema: Schema) -> list[Finding]:
    findings = []
    for name in sorted(schema.tables):
        if schema.outgoing(name) or schema.incoming(name):
            continue
        findings.append(
            Finding(
                rule_id="R004",
                rule_name="İlişkisiz tablo",
                severity=INFO,
                target=_q(schema, name),
                message=(
                    f'"{name}" tablosuna hiçbir yönde foreign key uğramıyor.'
                ),
                rationale=(
                    "Ya gerçekten tek başına duruyordur - bir kod listesi, "
                    "denetim kaydı, migration defteri - ya da uygulama kodunda, "
                    "veritabanının zorlamadığı bir ilişki üzerinden "
                    "birleştiriliyordur. Yetim satırlar ikinci durumdan doğar."
                ),
                confidence="heuristic",
                remediations=(
                    Remediation(
                        label="Tablonun bilinçli olarak bağımsız olduğunu doğrula",
                        ddl="",
                        risk="low",
                        recommended=True,
                        note=(
                            "Öyleyse kuralın yoksayma listesine ekle ki rapor "
                            "bilinen-doğru bulgularla dolmasın."
                        ),
                    ),
                    Remediation(
                        label="Eksik ilişkiyi tanımla",
                        ddl=(
                            f"ALTER TABLE {_q(schema, name)}\n"
                            f"    ADD CONSTRAINT {name}_<ust_tablo>_id_fkey\n"
                            f"        FOREIGN KEY (<ust_tablo>_id)\n"
                            f"        REFERENCES {schema.name}.<ust_tablo> (id)\n"
                            f"        ON DELETE RESTRICT ON UPDATE RESTRICT;"
                        ),
                        risk="medium",
                        requires_decision=True,
                        note="Şablon - üst tablo ve kolon adını doldur.",
                    ),
                ),
            )
        )
    return findings


# --------------------------------------------------------------------------
# R005 - circular foreign key chains
# --------------------------------------------------------------------------


def _cycle_key(cycle: list[str]) -> tuple[str, ...]:
    """Rotates a cycle so the same loop is never reported twice."""
    start = cycle.index(min(cycle))
    return tuple(cycle[start:] + cycle[:start])


def circular_foreign_keys(schema: Schema) -> list[Finding]:
    # A self-reference (employees.manager_id -> employees) is a normal way to
    # model a hierarchy, so it is not treated as a cycle.
    edges: dict[str, set[str]] = {}
    for fk in schema.foreign_keys:
        if fk.table != fk.target_table:
            edges.setdefault(fk.table, set()).add(fk.target_table)

    cycles: dict[tuple[str, ...], None] = {}
    visited: set[str] = set()
    stack: list[str] = []
    on_stack: set[str] = set()

    def visit(node: str) -> None:
        visited.add(node)
        stack.append(node)
        on_stack.add(node)
        for target in sorted(edges.get(node, ())):
            if target in on_stack:
                cycles.setdefault(_cycle_key(stack[stack.index(target) :]), None)
            elif target not in visited:
                visit(target)
        stack.pop()
        on_stack.discard(node)

    for table in sorted(schema.tables):
        if table not in visited:
            visit(table)

    findings = []
    for key in sorted(cycles):
        path = " -> ".join(key) + f" -> {key[0]}"
        findings.append(
            Finding(
                rule_id="R005",
                rule_name="Döngüsel foreign key zinciri",
                severity=ERROR,
                target=", ".join(key),
                message=f"Foreign key'ler döngü oluşturuyor: {path}.",
                rationale=(
                    "Döngüdeki hiçbir satır ilk sırada eklenemez; kayıtlar "
                    "ancak bir kısıt ertelenerek ya da bir kolon NULL bırakılıp "
                    "sonradan doldurularak oluşturulabilir. Grubu silmek de "
                    "aynı sorunu tersten yaşatır."
                ),
                remediations=(
                    Remediation(
                        label="Döngüyü kırmak için bir kısıtı ertele",
                        ddl=(
                            f"-- Döngüdeki en önemsiz bağı seç:\n"
                            f"ALTER TABLE {schema.name}.<tablo>\n"
                            f"    DROP CONSTRAINT <kisit>,\n"
                            f"    ADD CONSTRAINT <kisit>\n"
                            f"        FOREIGN KEY (<kolon>)\n"
                            f"        REFERENCES {schema.name}.<hedef> (id)\n"
                            f"        DEFERRABLE INITIALLY DEFERRED;"
                        ),
                        risk="medium",
                        requires_decision=True,
                        note=(
                            "Tek bir transaction'ın grubun tamamını eklemesine "
                            "izin verir."
                        ),
                    ),
                    Remediation(
                        label="En zayıf bağı ayrı bir tabloya taşı",
                        ddl="",
                        risk="high",
                        requires_decision=True,
                        note=(
                            "Yapısal çözüm: doğrudan referanslardan birini "
                            "bağlantı tablosuyla değiştirerek döngüyü ortadan "
                            "kaldır."
                        ),
                    ),
                ),
            )
        )
    return findings


# --------------------------------------------------------------------------
# R006 - duplicate and redundant indexes
# --------------------------------------------------------------------------


def redundant_index(schema: Schema) -> list[Finding]:
    findings = []
    for name in sorted(schema.tables):
        table = schema.tables[name]
        reported: set[str] = set()

        by_columns: dict[tuple[str, ...], list] = {}
        for index in table.indexes:
            by_columns.setdefault(index.columns, []).append(index)

        # Exact duplicates: same columns in the same order.
        for columns, group in sorted(by_columns.items()):
            if len(group) < 2:
                continue
            # Keep the primary key, then any unique index - those carry a
            # guarantee, not just an access path.
            group = sorted(
                group, key=lambda ix: (not ix.is_primary, not ix.is_unique, ix.name)
            )
            keep, extras = group[0], group[1:]
            for extra in extras:
                reported.add(extra.name)
                findings.append(
                    Finding(
                        rule_id="R006",
                        rule_name="Yinelenen index",
                        severity=WARNING,
                        target=f"{_q(schema, name)}.{extra.name}",
                        message=(
                            f'"{extra.name}" index\'i ({", ".join(columns)}) '
                            f'kolonlarını indeksliyor; "{keep.name}" bunu zaten '
                            f"kapsıyor."
                        ),
                        rationale=(
                            "Aynı index'in ikinci kopyası her insert, update ve "
                            "delete işleminde yeniden yazılır, disk ve önbellek "
                            "harcar ve planlayıcı tarafından birincisine tercih "
                            "edilmez."
                        ),
                        remediations=(
                            Remediation(
                                label=f"{extra.name} index'ini düşür",
                                ddl=f"DROP INDEX {schema.name}.{extra.name};",
                                risk="medium" if extra.is_unique else "low",
                                recommended=not extra.is_unique,
                                note=(
                                    "Bu index aynı zamanda benzersizliği "
                                    "zorluyor - kısıt adına bağlı bir şey "
                                    "olmadığını kontrol et."
                                    if extra.is_unique
                                    else "Saf kopya; kaldırmak güvenli."
                                ),
                            ),
                        ),
                    )
                )

        # Prefix redundancy: an index on (a) is dead weight when (a, b) exists.
        for index in sorted(table.indexes, key=lambda ix: ix.name):
            if index.is_primary or index.is_unique or index.name in reported:
                continue
            wider = [
                other.name
                for other in table.indexes
                if other.name != index.name
                and len(other.columns) > len(index.columns)
                and other.covers(index.columns)
            ]
            if not wider:
                continue
            covering = sorted(wider)[0]
            findings.append(
                Finding(
                    rule_id="R006",
                    rule_name="Gereksiz index ön eki",
                    severity=INFO,
                    target=f"{_q(schema, name)}.{index.name}",
                    message=(
                        f'"{index.name}" ({", ".join(index.columns)}) index\'i, '
                        f'"{covering}" index\'inin baştan alt kümesi.'
                    ),
                    rationale=(
                        "Bileşik bir index, baştaki kolonlarından başlayan "
                        "aramaları zaten karşılar; dar index yalnızca yazma "
                        "maliyeti ekler."
                    ),
                    remediations=(
                        Remediation(
                            label=f"{index.name} index'ini düşür",
                            ddl=f"DROP INDEX {schema.name}.{index.name};",
                            risk="low",
                            recommended=True,
                            note=(
                                f'"{covering}" aynı aramaları karşılamaya '
                                f"devam eder."
                            ),
                        ),
                    ),
                )
            )
    return findings


# --------------------------------------------------------------------------
# R007 - foreign key type mismatch
# --------------------------------------------------------------------------


def foreign_key_type_mismatch(schema: Schema) -> list[Finding]:
    findings = []
    for fk in schema.foreign_keys:
        source = schema.tables.get(fk.table)
        target = schema.tables.get(fk.target_table)
        if source is None or target is None:
            continue
        for column_name, target_name in zip(fk.columns, fk.target_columns):
            column = source.column(column_name)
            target_column = target.column(target_name)
            if column is None or target_column is None:
                continue
            if column.type_oid == target_column.type_oid:
                continue
            findings.append(
                Finding(
                    rule_id="R007",
                    rule_name="Foreign key tip uyuşmazlığı",
                    severity=ERROR,
                    target=f"{_q(schema, fk.table)}.{column_name}",
                    message=(
                        f"{fk.table}.{column_name} kolonu {column.data_type}, "
                        f"ama referans verdiği {fk.target_table}.{target_name} "
                        f"kolonu {target_column.data_type}."
                    ),
                    rationale=(
                        "PostgreSQL karşılaştırılabilir ama farklı tipler "
                        "arasında foreign key'e izin verir. Bu durumda her join "
                        "bir cast gerektirir; bu index kullanımını "
                        "engelleyebilir ve dar taraf geniş taraftan çok önce "
                        "taşar."
                    ),
                    remediations=(
                        Remediation(
                            label=(
                                f"{fk.table}.{column_name} kolonunu "
                                f"{target_column.data_type} tipine genişlet"
                            ),
                            ddl=(
                                f"ALTER TABLE {_q(schema, fk.table)}\n"
                                f"    ALTER COLUMN {column_name} TYPE "
                                f"{target_column.data_type};"
                            ),
                            risk="medium",
                            recommended=True,
                            note=(
                                "Tabloyu baştan yazar ve index'lerini yeniden "
                                "kurar."
                            ),
                        ),
                    ),
                )
            )
    return findings


# --------------------------------------------------------------------------
# R008 - unindexed foreign keys
# --------------------------------------------------------------------------


def unindexed_foreign_key(schema: Schema) -> list[Finding]:
    findings = []
    for fk in schema.foreign_keys:
        table = schema.tables.get(fk.table)
        if table is None or not fk.columns:
            continue
        if any(index.covers(fk.columns) for index in table.indexes):
            continue

        columns = ", ".join(fk.columns)
        index_name = f"idx_{fk.table}_{'_'.join(fk.columns)}"
        findings.append(
            Finding(
                rule_id="R008",
                rule_name="İndekslenmemiş foreign key",
                severity=WARNING,
                target=f"{_q(schema, fk.table)}.{columns}",
                message=(
                    f"{fk.table} tablosunda ({columns}) ile başlayan bir index "
                    f"yok."
                ),
                rationale=(
                    "PostgreSQL foreign key'in üst tarafını indeksler, alt "
                    "tarafını asla. Bu ilişki üzerinden yapılan her join ve üst "
                    "tabloda yapılan her silme - ki alt kayıtları aramak "
                    "zorundadır - sıralı taramaya düşer. Bileşik birincil "
                    "anahtarda yalnızca ilk kolon kapsandığı için bağlantı "
                    "tablolarının ikinci kolonu genelde buraya düşer."
                ),
                remediations=(
                    Remediation(
                        label=f"({columns}) üzerinde index oluştur",
                        ddl=(
                            f"CREATE INDEX {index_name}\n"
                            f"    ON {_q(schema, fk.table)} ({columns});"
                        ),
                        risk="low",
                        recommended=True,
                        note=(
                            "Yoğun bir tabloda yazma kilidi almamak için "
                            "CONCURRENTLY ekle."
                        ),
                    ),
                ),
            )
        )
    return findings


# --------------------------------------------------------------------------
# R009 - relationships the database does not enforce
# --------------------------------------------------------------------------


def _guess_target_table(schema: Schema, base: str) -> str | None:
    candidates = [base, f"{base}s", f"{base}es"]
    if base.endswith("y"):
        candidates.append(f"{base[:-1]}ies")
    for candidate in candidates:
        if candidate in schema.tables:
            return candidate
    return None


def implied_foreign_key(schema: Schema) -> list[Finding]:
    findings = []
    for name in sorted(schema.tables):
        table = schema.tables[name]
        constrained = {column for fk in schema.outgoing(name) for column in fk.columns}
        for column in table.columns:
            if not column.name.endswith("_id") or column.name in constrained:
                continue
            target = _guess_target_table(schema, column.name[:-3])
            if target is None or target == name:
                continue

            findings.append(
                Finding(
                    rule_id="R009",
                    rule_name="Foreign key ile korunmayan örtük ilişki",
                    severity=WARNING,
                    target=f"{_q(schema, name)}.{column.name}",
                    message=(
                        f'"{name}.{column.name}" bir "{target}" referansına '
                        f"benziyor ama bunu zorlayan bir foreign key yok."
                    ),
                    rationale=(
                        "Hiçbir üst satırla eşleşmeyen bir değeri engelleyen "
                        "yok. Veritabanı yetim kayıtları sessizce saklar; "
                        "bunlar genellikle çok sonra, inner join'den düşen "
                        "satırlar olarak ortaya çıkar."
                    ),
                    confidence="heuristic",
                    remediations=(
                        Remediation(
                            label="Önce yetim kayıtları kontrol et",
                            ddl=(
                                f"SELECT COUNT(*)\n"
                                f"FROM {_q(schema, name)} child\n"
                                f"LEFT JOIN {_q(schema, target)} parent\n"
                                f"       ON parent.id = child.{column.name}\n"
                                f"WHERE child.{column.name} IS NOT NULL\n"
                                f"  AND parent.id IS NULL;"
                            ),
                            risk="low",
                            recommended=True,
                            note=(
                                "Salt okunur. Aşağıdaki kısıt, bu sorgu 0 "
                                "dönene kadar eklenemez."
                            ),
                        ),
                        Remediation(
                            label="Foreign key'i ekle",
                            ddl=(
                                f"ALTER TABLE {_q(schema, name)}\n"
                                f"    ADD CONSTRAINT {name}_{column.name}_fkey\n"
                                f"        FOREIGN KEY ({column.name})\n"
                                f"        REFERENCES {_q(schema, target)} (id)\n"
                                f"        ON DELETE RESTRICT ON UPDATE RESTRICT;"
                            ),
                            risk="medium",
                            requires_decision=True,
                            note=(
                                "Tahmin edilen hedef tablonun doğru olduğunu "
                                "teyit et."
                            ),
                        ),
                    ),
                )
            )
    return findings


# --------------------------------------------------------------------------
# R010 - the same column name declared differently
# --------------------------------------------------------------------------


def inconsistent_column_type(schema: Schema) -> list[Finding]:
    usage: dict[str, dict[str, list[str]]] = {}
    for name in sorted(schema.tables):
        for column in schema.tables[name].columns:
            usage.setdefault(column.name, {}).setdefault(column.data_type, []).append(
                name
            )

    findings = []
    for column_name in sorted(usage):
        variants = usage[column_name]
        if len(variants) < 2:
            continue

        # The type used by the most tables wins; ties go to the longer
        # declaration, since that is the one able to hold every existing value.
        preferred = sorted(
            variants,
            key=lambda type_name: (-len(variants[type_name]), -len(type_name)),
        )[0]
        summary = "; ".join(
            f"{', '.join(sorted(tables))} tablosunda {type_name}"
            for type_name, tables in sorted(variants.items())
        )

        remediations = []
        for type_name, tables in sorted(variants.items()):
            if type_name == preferred:
                continue
            for table_name in sorted(tables):
                remediations.append(
                    Remediation(
                        label=(
                            f"{table_name}.{column_name} kolonunu {preferred} "
                            f"tipine hizala"
                        ),
                        ddl=(
                            f"ALTER TABLE {_q(schema, table_name)}\n"
                            f"    ALTER COLUMN {column_name} TYPE {preferred};"
                        ),
                        risk="medium",
                        requires_decision=True,
                        note=(
                            "Yalnızca iki kolon gerçekten aynı türde veri "
                            "tutuyorsa - ortak ad bunun kanıtı değildir."
                        ),
                    )
                )

        findings.append(
            Finding(
                rule_id="R010",
                rule_name="Ortak kolon adı için tutarsız tip",
                severity=INFO,
                target=column_name,
                message=(
                    f'"{column_name}" kolonu farklı tiplerde tanımlanmış: '
                    f"{summary}."
                ),
                rationale=(
                    "Aynı anlama gelen kolonlar aynı şekilde tanımlanmalıdır. "
                    "Karışık genişlikler, bir tabloya sığan ama aynı veri başka "
                    "tabloya taşındığında reddedilen değerlere yol açar."
                ),
                confidence="heuristic",
                remediations=tuple(remediations),
            )
        )
    return findings
